language: java

jdk:
- oraclejdk8

install:
- true

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

script:
- ./gradlew clean build --stacktrace -Dstubrunner.skip-local-repo=true

env:
- TERM=dumb

