language: groovy
jdk:
- oraclejdk7

install:
- true

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

script:
- ./gradlew build

env:
- TERM=dumb

after_success:
- ./gradlew test jacocoTestReport coveralls -Pcoverage